config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root to: 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :tasks
  get "/search", to: "tasks#search", as: "search_tasks"
  namespace :admin do
    resources :users
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user, optional: true
    has_many :labelings, dependent: :destroy
    has_many :labels, through: :labelings, source: :label

    validates :name, presence: true
    # validates :details, presence: true
    # validates :status, presence: true

    enum priority: {low: 0, medium: 1, high: 2}
    
    scope  :order_by_created_at, ->  {order(created_at: :desc)}
    scope  :order_by_deadline,  ->  {order(expiry_date: :desc)}
    scope  :order_by_ty_button,  ->  {order(priority: :desc)}
    scope  :order_by_priority,  ->  (priority){where(priority: priority)}
    scope  :order_by_status,  ->  (status){where(status: status)}
    scope  :title_search, -> (search_key){where("name LIKE ?","%#{search_key}%")}
    scope :label_search, -> (search_label){
        tasks = Labeling.where(label_id: search_label)
        ids = tasks.map{ |task| task.task_id } 
        where(id: ids)
    }
    
    paginates_per 5

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_login
  before_action :set_task, only: %i[ show edit update destroy ]

  def index
    # raise
    if params[:by_deadline] == "true"
      @tasks = current_user.tasks.all.order('expired_at DESC').page params[:page]
    elsif params[:by_priority] == "true"
      @tasks = current_user.tasks.all.order('priority DESC').page params[:page]
    else
      @tasks = current_user.tasks.all.order('created_at DESC').page params[:page]
    end
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = current_user.tasks.build(task_params)
    @task.user_id = current_user.id
    # p current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task , notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # def search

  #   session[:search] = {'name' => params[:search_title], 'status' => params[:search_status], 'priority' => params[:search_priority]}
   
  #   if params[:search_title].present?
  #     if params[:search_status].present?
  #       if params[:search_priority].present?
  #         @tasks = Task.all.title_search(params[:search_title]).order_by_status(params[:search_status]).order_by_priority(params[:search_priority]).page params[:page] 
  #       else
  #         @tasks = Task.all.title_search(params[:search_title]).order_by_status(params[:search_status]).page params[:page] 
  #       end
  #     elsif params[:search_priority].present?
  #       @tasks = Task.all.title_search(params[:search_title]).order_by_priority(params[:search_priority]).page params[:page] 
  #     else
  #       @tasks = Task.all.title_search(params[:search_title]).page params[:page] 

  #     end


  #   elsif params[:search_status].present?
      
  #     if params[:search_priority].present?
  #       @tasks = Task.all.order_by_status(params[:search_status]).order_by_priority(params[:search_priority]).page params[:page] 
  #     else
  #       @tasks = Task.all.order_by_status(params[:search_status]).page params[:page] 
  #     end

    
  #   elsif params[:search_priority].present?
      
  #     if params[:search_status].present?
  #       @tasks = Task.all.order_by_priority(params[:search_priority]).order_by_status(params[:search_status]).page params[:page] 
  #     else
  #       @tasks = Task.all.order_by_priority(params[:search_priority]).page params[:page] 
  #     end

    
  #   else
  #     @tasks = Task.all
  #   end
  
  #   #@labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
    
  #   render :index
  # end

  def search 
    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
    session[:search] = {'name' => params[:search_title], 'status' => params[:search_status], 'priority' => params[:search_priority]}
   
    if params[:search_title].present?
      if params[:search_status].present?
        if params[:search_priority].present?
          if params[:search_label].present?
          @tasks = current_user.tasks.title_search(params[:search_title]).order_by_status(params[:search_status]).order_by_priority(params[:search_priority]).label_search(params[:search_label]).page params[:page] 
          else 
            @tasks = current_user.tasks.title_search(params[:search_title]).order_by_status(params[:search_status]).order_by_priority(params[:search_priority]).page params[:page] 
          end
        else
          @tasks = current_user.tasks.title_search(params[:search_title]).order_by_status(params[:search_status]).page params[:page] 
        end
      elsif params[:search_priority].present?
        @tasks = current_user.tasks.title_search(params[:search_title]).order_by_priority(params[:search_priority]).page params[:page] 
      else
        @tasks = current_user.tasks.title_search(params[:search_title]).page params[:page] 

      end


    elsif params[:search_status].present?
      
      if params[:search_priority].present?
        if params[:search_label].present?
          @tasks = current_user.tasks.order_by_status(params[:search_status]).order_by_priority(params[:search_priority]).label_search(params[:search_label]).page params[:page] 
        else
           @tasks = current_user.tasks.order_by_status(params[:search_status]).order_by_priority(params[:search_priority]).page params[:page]
        end
          
      else
        @tasks = current_user.tasks.order_by_status(params[:search_status]).page params[:page] 
      end

      
    elsif params[:search_priority].present?
      
      if params[:search_status].present?
        if params[:search_label].present?
          @tasks = current_user.tasks.order_by_priority(params[:search_priority]).order_by_status(params[:search_status]).label_search(params[:search_label]).page params[:page]
        else
          @tasks = current_user.tasks.order_by_priority(params[:search_priority]).order_by_status(params[:search_status]).page params[:page] 
        end
        
      else
        @tasks = current_user.tasks.order_by_priority(params[:search_priority]).page params[:page] 
      end


    elsif params[:search_label].present?
      
      if params[:search_status].present?
        if params[:search_priority].present?
          @tasks = current_user.tasks.order_by_priority(params[:search_priority]).order_by_status(params[:search_status]).label_search(params[:search_label]).page params[:page]
        else
          @tasks = current_user.tasks.label_search(params[:search_label]).order_by_status(params[:search_status]).page params[:page] 
        end
        
      else
        @tasks = current_user.tasks.label_search(params[:search_label]).page params[:page] 
      end
      
    else
      @tasks = current_user.tasks
    end
  
    # @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
    
    render :index
  end



  private

    def set_task
      @task = Task.find(params[:id])
    end


    def task_params
      params.require(:task).permit(:name, :details, :expired_at, :status, :priority, label_ids: [])
    end

    def require_login
      unless current_user
        flash[:error] = "You must be logged in to access this section"
        redirect_to new_session_path
      end
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
    <div class="alert alert-danger">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details %>
  </div>
  <div class="field">
    <%= form.label :expired_at %>
    <%= form.date_field :expired_at %> 
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, ['', 'Unstarted', 'In progress', 'Completed'] %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, Task.priorities.keys %>
  </div>


  <div class= "field">
    <label>Labels  : </label>
    <% Label.all.each do |label| %>
        <%= form.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
        <%= label.name %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="pb-5"></div>

<div class="d-flex justify-content-between">

<h1>Tasks</h1>

<div><a href="<%= new_task_path %>" class="btn btn-outline-success mt-2 ms-5">New Task</a></div>

<div><a href="<%= admin_users_path %>" class="btn btn-outline-success mt-2 ms-5">Management Users</a></div>
<div class="d-flex" style="margin-right: 0;">
        <%= form_with(url: search_tasks_path, method: :get, local: true) do |f| %>
        <% if defined? @search_title %>
          <%= f.text_field :search_title, value: @search_title, class:'form-control me-2'%>
        <% else %>
        <span class="fs-6">By name </span>   <%= f.text_field :search_title %>
        <% end %>
        <span class="fs-6"> By status </span> <%= f.select :search_status, ['Unstarted', 'In progress', 'Completed'], prompt: 'status' %>
        <span class=""> By priority </span> <%= f.select :search_priority, Task.priorities.map { |k, v| [k, v] }, class: 'search_priority form-control', prompt: 'priority'%>


          <span class="fs-6">
          By label <%= f.select :search_label, Label.all.collect { |p| [ p.name, p.id ] }, include_blank: true %>
          </span>
          <%= f.submit 'search' ,class:'btn btn-outline-success me-5'%>

        <% end %>
      </div>
</div>


<table class="table">
  <thead class="table-primary">
    <tr>
    <th scope="col">Author</th>
      <th scope="col">Name Tasks</th>
      <th scope="col">Details</th>
      <th scope="col"><a href="<%= tasks_path(by_deadline: "true")%> " class="text-primary">DeadLine<i class="bi bi-chevron-down"></i></a></th>
      <th scope="col">Status</th>
      <th scope="col"><a href="<%= tasks_path(by_priority: "true")%> " class="text-primary">Priority<i class="bi bi-chevron-down"></i></a></th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
      <td class="task_row"><%= task.user.name %></td>
        <td class="task_row"><%= task.name %></td>
        <td><%= task.details %></td>
        <td><%= task.expired_at.to_date %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= link_to 'Show', task, :class => "btn btn-outline-primary" %></td>
        <td><%= link_to 'Edit', edit_task_path(task), :class => "btn btn-outline-success" %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-outline-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr>

<br>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<div class="container mt-5">
  <div class="card text-center">
    <div class="card-header">
      <strong>Name:</strong>
      <%= @task.name %>
    </div>
    <div class="card-body">
      <h5 class="card-title">  <strong>Details: </strong><%= @task.details %></h5>
      <h5 class="card-title"><strong>Expired_at: </strong><%= @task.expired_at.to_date %></h5>
      <h5 class="card-title"><strong>Status: </strong><%= @task.status %></h5>
      <h5 class="card-title"><strong>Priority: </strong><%= @task.priority %></h5>
      <h5 class="card-title">
        <div class="btn btn-info position-relative">
          Labels
          <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-success">
            <%= @task.labels.count%>
          </span>
        </div>
      </h5>
      <% @task.labels.each do |p| %>
      <span><span class="badge bg-success"><%= p.name %></span></span>
      <% end %>
    </div>
    <div class="card-footer text-muted">
  <%= link_to 'Edit', edit_task_path(@task) %> |
  <%= link_to 'Back', tasks_path %>
  
    </div>
  </div>
</div>