config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root to: 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :tasks
  get "/search", to: "tasks#search", as: "search_tasks"
  namespace :admin do
    resources :users
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin/user.rb
class Admin::User < ApplicationRecord
    attr_accessor :skip_validations

    validates :password, presence: true, length: {minimum: 6}, unless: :skip_validations

    paginates_per 5
    
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :skip_validations
    has_many :tasks, dependent: :destroy
    # validate :name
    validates :email, presence: true, length: { maximum: 255},
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
    before_validation {email.downcase!}
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}, unless: :skip_validations
    def current_user
      session[:user_id]
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    # before_action :if_login, only: %i[ new ]
    before_action :find_id, only: %i[edit update destroy show]

    def index
        if current_user.is_admin
            @users = User.all.includes(:tasks).page params[:page]
        else
            flash[:danger] = "Only admin can access"
            redirect_to tasks_path
        end
    end

    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        flash[:success] = "User create successfuly"
        redirect_to admin_users_path
      else
        render :new
      end
    end
  
    def show
    end

    def edit
    end

    def update
        @user.skip_validations = true
        if @user.update(user_params)
          flash[:success] = "Profile updated"
          redirect_to admin_users_path
        else
          render :edit
        end
      end

    def destroy
      @user.destroy
      redirect_to admin_users_path, notice:"Admin deleted"
    end


    private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :is_admin)
    end
    def find_id
        @user = User.find(params[:id])
    end

#   def if_login
#     if current_user.present?
#       flash[:error] = "You are already connected"
#       redirect_to tasks_path
#     end
#   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :if_login, only: %i[ new ]
  before_action :find_id, only: %i[edit update destroy]

  def new
    if current_user.present?
      redirect_to tasks_path
    else
      @user = User.new
    end
  end
  
  def create
    @user = User.new(user_params)
    @user.is_admin = false
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Successfully and Already Connected"
      redirect_to @user
    else
      render :new
    end
  end
  
  def show
    if params[:id].to_i != current_user.id && !current_user.is_admin
      flash[:error] = "This is not your page"
      redirect_to tasks_path
    else
      @user = User.find(params[:id])
    end
  end

  
  def edit
    # @user = User.find(params[:id])
  end


  def update
    # @user = User.find(params[:id])
    @user.skip_validations = true
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      if current_user.is_admin
      redirect_to admin_users_path
      else redirect_to tasks_path
      end
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice:"User deleted"
  end
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def find_id
    @user = User.find(params[:id])
  end

  def if_login
    if current_user.present?
      flash[:error] = "You are already connected"
      redirect_to tasks_path
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: @user do |t| %>
      <div class="row mb-5">
        <%= t.label :name, class: "col-md-4" %>
        <%= t.text_field :name, class: "col-md-4"%>
      </div>

      <div class="row mb-5">
        <%= t.label :email, class: "col-md-4"%>
        <%= t.email_field :email, class: "col-md-4"%>
      </div>

      <div class="row mb-5">
        <%= t.label :password, class: "col-md-4"%>
        <%= t.password_field :password, class: "col-md-4"%>
      </div>

      <div class="row">
        <%= t.label :password_confirmation, class: "col-md-4"%>
        <%= t.password_field :password_confirmation, class: "col-md-4"%>
      </div>

      <div class="text-center mt-5">
        <%= t.submit "Je m'inscris", class: "btn btn-success"%>
      </div>
      <div class="text-center mt-3">
        <a class="fs-6 px-3 py-1 btn" href="<%=new_session_path%>" style="background-color: #007693; font-family: 'ZCOOL KuaiLe', cursive;">J'ai deja un compte</a>
      </div>
  <% end%>

app/views/users/edit.html.erb
Edit Users
<%= form_with model: @user do |t| %>
      <div class="row mb-5">
        <%= t.label :name, class: "col-md-4" %>
        <%= t.text_field :name, class: "col-md-4"%>
      </div>

      <div class="row mb-5">
        <%= t.label :email, class: "col-md-4"%>
        <%= t.email_field :email, class: "col-md-4"%>
      </div>

      <div class="row mb-5">
        <%= t.label :password, class: "col-md-4"%>
        <%= t.password_field :password, class: "col-md-4"%>
      </div>

      <div class="row">
        <%= t.label :password_confirmation, class: "col-md-4"%>
        <%= t.password_field :password_confirmation, class: "col-md-4"%>
      </div>

      <div class="text-center mt-5">
        <%= t.submit "Enregistrer", class: "btn btn-success"%>
      </div>
  <% end%>

app/views/users/new.html.erb
<div class="container mt-5">
  <div class="text-center">
    <span class="fs-3 px-5 py-3" style="background-color: #007693; font-family: 'ZCOOL KuaiLe', cursive;"> S'inscrire</span>
  </div>
</div>
<div class="container mx-auto">
  <div class="row mt-5">
    <%= render 'form', user: @user %>
</div>

app/views/users/show.html.erb
<div class="container mt-5" >
  <div class="card">
    <h5 class="card-header text-center bg-secondary">Account Details</h5>
    <div class="card-body">
      <h5 class="card-title">Your Name: <span   class="ms-5 fs-2" style="font-family: 'Gemunu Libre', sans-serif;"><%= current_user.name%></span></h5>
      <h5 class="card-title">Your E-mail: <span class="ms-5 fs-2" style="font-family: 'Gemunu Libre', sans-serif;"><%=current_user.email%></span></h5>
      <a data-confirm="Are you sure?" data-method="delete" href="<%= session_path(current_user.id)%>" class="btn btn-danger text-white">Logout</a>
      <a href="<%= tasks_path %>" class="btn btn-primary text-white">Home</a>
      <a href="<%= edit_user_path(current_user.id) %>" class="btn btn-info text-white">Edit</a>
    </div>
  </div>
</div>