config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root to: 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :tasks
  get "/search", to: "tasks#search", as: "search_tasks"
  namespace :admin do
    resources :users
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin/user.rb
class Admin::User < ApplicationRecord
    attr_accessor :skip_validations

    validates :password, presence: true, length: {minimum: 6}, unless: :skip_validations

    paginates_per 5
    
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :skip_validations
    has_many :tasks, dependent: :destroy
    # validate :name
    validates :email, presence: true, length: { maximum: 255},
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
    before_validation {email.downcase!}
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}, unless: :skip_validations
    def current_user
      session[:user_id]
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    # before_action :if_login, only: %i[ new ]
    before_action :find_id, only: %i[edit update destroy show]

    def index
        if current_user.is_admin
            @users = User.all.includes(:tasks).page params[:page]
        else
            flash[:danger] = "Only admin can access"
            redirect_to tasks_path
        end
    end

    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        flash[:success] = "User create successfuly"
        redirect_to admin_users_path
      else
        render :new
      end
    end
  
    def show
    end

    def edit
    end

    def update
        @user.skip_validations = true
        if @user.update(user_params)
          flash[:success] = "Profile updated"
          redirect_to admin_users_path
        else
          render :edit
        end
      end

    def destroy
      @user.destroy
      redirect_to admin_users_path, notice:"Admin deleted"
    end


    private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :is_admin)
    end
    def find_id
        @user = User.find(params[:id])
    end

#   def if_login
#     if current_user.present?
#       flash[:error] = "You are already connected"
#       redirect_to tasks_path
#     end
#   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :if_login, only: %i[ new ]
  before_action :find_id, only: %i[edit update destroy]

  def new
    if current_user.present?
      redirect_to tasks_path
    else
      @user = User.new
    end
  end
  
  def create
    @user = User.new(user_params)
    @user.is_admin = false
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Successfully and Already Connected"
      redirect_to @user
    else
      render :new
    end
  end
  
  def show
    if params[:id].to_i != current_user.id && !current_user.is_admin
      flash[:error] = "This is not your page"
      redirect_to tasks_path
    else
      @user = User.find(params[:id])
    end
  end

  
  def edit
    # @user = User.find(params[:id])
  end


  def update
    # @user = User.find(params[:id])
    @user.skip_validations = true
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      if current_user.is_admin
      redirect_to admin_users_path
      else redirect_to tasks_path
      end
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice:"User deleted"
  end
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def find_id
    @user = User.find(params[:id])
  end

  def if_login
    if current_user.present?
      flash[:error] = "You are already connected"
      redirect_to tasks_path
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with model: @user do |t| %>
      <div class="row mb-5">
        <%= t.label :name, class: "col-md-4" %>
        <%= t.text_field :name, class: "col-md-4"%>
      </div>

      <div class="row mb-5">
        <%= t.label :email, class: "col-md-4"%>
        <%= t.email_field :email, class: "col-md-4"%>
      </div>

      <div class="row mb-5">
        <%= t.label :password, class: "col-md-4"%>
        <%= t.password_field :password, class: "col-md-4"%>
      </div>

      <div class="row">
        <%= t.label :password_confirmation, class: "col-md-4"%>
        <%= t.password_field :password_confirmation, class: "col-md-4"%>
      </div>

      <div class="text-center mt-5">
        <%= t.submit "Je m'inscris", class: "btn btn-success"%>
      </div>
      <div class="text-center mt-3">
        <a class="fs-6 px-3 py-1 btn" href="<%=new_session_path%>" style="background-color: #007693; font-family: 'ZCOOL KuaiLe', cursive;">J'ai deja un compte</a>
      </div>
  <% end%>

app/views/admin/users/edit.html.erb
<p>Edit admin</p>
<%= form_with model: @user, url: admin_user_path do |t| %>
      <div class="row mb-5">
        <%= t.label :name, class: "col-md-4" %>
        <%= t.text_field :name, class: "col-md-4"%>
      </div>

      <div class="row mb-5">
        <%= t.label :email, class: "col-md-4"%>
        <%= t.email_field :email, class: "col-md-4"%>
      </div>

      <div class="row mb-5">
        <%= t.label :password, class: "col-md-4"%>
        <%= t.password_field :password, class: "col-md-4"%>
      </div>
      
      <div class="row text-center">
        <%= t.label :is_admin, class: "col-md-4"%>
        <%= t.check_box :is_admin, class: "col-md-4 fs-5", :style => "width: 30px; height: 30px;"%>
      </div>

      <div class="text-center mt-5">
        <%= t.submit "Enregistrer", class: "btn btn-success"%>
      </div>
  <% end%>

app/views/admin/users/index.html.erb
<div class="mt-5"></div>
<div>
<a href="<%=new_admin_user_path %>" class="btn btn-outline-success">New User</a>
</div>
<h1 class="mt-3">Users</h1>
<table class="table mt-5">
  <thead class="table-primary">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Nbre Tasks</th>
      <th scope="col">Status</th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="user_row"><%= user.name %></td>
        <td><%= user.email %></td>

        <td><%= user.tasks.count %></td>
        
        <% if user.is_admin %>
            <td>Administrateur</td>
        <% else %>
            <td>Utilisateur simple</td>
        <% end %>

        <!-- Show -->
          <td><span <% if current_user.id == user.id %>class="d-none" <% end %>><%= link_to 'Show', admin_user_path(user.id), :class => "btn btn-outline-primary user_row" %></span></td>
        <!-- Edit -->
          <td><span <% if current_user.id == user.id %>class="d-none" <% end %>><%= link_to 'Edit', edit_admin_user_path(user.id), :class => "btn btn-outline-success" %></span></td>
        <!-- Destroy -->
          <% if user.is_admin %>
          <td><span <% if current_user.id == user.id %>class="d-none" <% end %>><%= link_to 'Destroy', admin_user_path(user.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-outline-danger" %></span></td>
        <% else %>
          <td><%= link_to 'Destroy', user_path(user.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-outline-info" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @users %>

app/views/admin/users/new.html.erb
<h1>New user</h1>
<div class="container mt-5">
<div class="text-center">
<%= form_with model: @user, url: admin_users_path do |t| %>
      <div class="row mb-5">
        <%= t.label :name, class: "col-md-4"%>
        <%= t.text_field :name, class: "col-md-4"%>
      </div>

      <div class="row mb-5">
        <%= t.label :email, class: "col-md-4"%>
        <%= t.email_field :email, class: "col-md-4"%>
      </div>

      <div class="row mb-5">
        <%= t.label :password, class: "col-md-4"%>
        <%= t.password_field :password, class: "col-md-4"%>
      </div>

      <div class="row text-center">
        <%= t.label :is_admin, class: "col-md-4"%>
        <%= t.check_box :is_admin, class: "col-md-4 fs-5", :style => "width: 30px; height: 30px;"%>
      </div>

      <div class="text-center mt-5">
        <%= t.submit "J'inscris un utilisateur", class: "btn btn-success"%>
      </div>
  <% end%>
</div>
</div>

app/views/admin/users/show.html.erb
<% if @user.id == current_user.id %>
<div class="container mt-5" >
  <div class="card">
    <h5 class="card-header text-center bg-secondary">Account Details</h5>
    <div class="card-body">
      <h5 class="card-title">Your Name: <span   class="ms-5 fs-2" style="font-family: 'Gemunu Libre', sans-serif;"><%= @user.name%></span></h5>
      <h5 class="card-title">Your E-mail: <span class="ms-5 fs-2" style="font-family: 'Gemunu Libre', sans-serif;"><%= @user.email%></span></h5>
      <% if @user.is_admin %> <h5 class="card-title">Status: <span class="ms-5 fs-2" style="font-family: 'Gemunu Libre', sans-serif;">Administrateur</span></h5><% end %>

      <% if @user.id == current_user.id %>
      <a data-confirm="Are you sure?" data-method="delete" href="<%= session_path(current_user.id) %>" class="btn btn-danger text-white">Logout</a>
      <a href="<%= edit_admin_user_path(current_user.id) %>" class="btn btn-info text-white">Edit</a>
      
      <% end %>

    </div>
  </div>
</div>
<% end %>

<% if current_user.is_admin && @user.id != current_user.id %>
<div class="h1 mt-5">Tasks list</div>
<table class="table mt-5">
  <thead class="table-primary">
    <tr>
      <th scope="col">Author Name</th>
      <th scope="col">Tasks Name</th>
      <th scope="col">Details</th>
      <th scope="col">DeadLine<i class="bi bi-chevron-down"></i></a></th>
      <th scope="col">Status</th>
      <th scope="col">Priority<i class="bi bi-chevron-down"></i></a></th>
      <th scope="col"></th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @user.tasks.each do |task| %>
      <tr>
        <td><%= task.user.name %></td>
        <td class="task_row"><%= task.name %></td>
        <td><%= task.details %></td>
        <td><%= task.expired_at.to_date %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>